=== Dohwon/Homepage-dowon/schemas/public-cover.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["alt", "caption", "content_type", "content_hex"],
  "properties": {
    "alt": {"type": "string", "minLength": 1},
    "caption": {"type": "string", "minLength": 1},
    "content_type": {"enum": ["image/png", "image/jpeg", "image/webp"]},
    "content_hex": {"type": "string", "minLength": 8, "maxLength": 4194304, "pattern": "^[0-9a-f]+$"}
  }
}

=== Dohwon/Homepage-dowon/public-bundle/projects/260802-map-diary-v5/cover.json
{"alt":"지도 기록 다이어리 v5 구현 화면","caption":"실제 구현 화면","content_hex":"89504e470d0a1a0a0000000d49484452000001860000034c0802000000d70e9d490000100049444154789cecfd09b875c955100c57ede98c777ce7b1e7319da4d3191a826612507f0341404514850f4454e003143efc4011f8151f06fd15ff4f5124c8a8e8affe7e46018124249090a43374d24927e9e1ed771eef7def70a63dd5b786daf33ee7ec73eeb9f79edbfd563ae7ddb776ed55abaa56ad5ab5d6aa55d6f6e64d29a552eaceef9ddf3bbf777ef7fd5776b66e2a25e04150a267917a56f4280bf9f1b3a26759f62dfe4bcf72c8b782d0c08f5328a4cba891b88d853f1ab7b1f067db7615e58fc2270ccbebc20e3246f4c30e71838a9534d2e547b7fde5342e93c29f356e8af0d1207715b7b1f077755c9402da3646c047e0f8bcbd015212628abfaaf04b3364e85be626385ba67a4bf0057125c390fb52fb5eb43d8c728ce1df86f178eb9c50d3ab1ec5ddee192648c3d8db9ed9df71d98dda27c78dbb5ed3ffcbb267c26c8e51fead22fa8765576e6fde20c6152fc799a488ad0e7b3bb640a5cf15b542ca293fdf5fe42b7dae578ff847e8a55170a3414251ba0c9595d18340c9a8bc67d48c9bc6c26a9c73403a76ee3e9f02384d01a604f9b2ec19c867d257ccaf0a5f6bfa8f668981b4ad78398eb3555c01d752921f9757322a98cd8f90514a94e4a7e02b14f8942a851fe3361d7cc6adb4de2af0e96d79bd55e08b1837ee43c14553f9c8078220801151c46342fae53f42ec188306586a3c191fc588cd725c425db4f2b8bf4cc6652af8339f2ff4cc324a95f972e0c625e247fca8d2f45c42ff0a376e370451bf10f138c57c4c458bb9cce5c7cf8ab65e11ebcb97d18b79b4412d851f9729e2c03374186e63e18fc66d2cfc5d6d3b7c1b866a58bb6007c5e2556a4dd945dc88224249225915f82fe371d961dba7c08de723d3ffaee23607e3a2442225c10450fa1bc68d9e805119b81e23ff0b9181aac2b318925fbdcc78f882e7dec4df5685bf3bdf5683af47286a233f87212c0d30222131645623e96728639ac491f05b91fe76f7c66562f8077f5ce60ab74cffef1e6e7bdff63cfdc36fa8e91f2740504aff726be33a7ec2bc8b199c10f1b366ab86cce5c7cf2a549a3516bed57c31a5a128851f9729e2106db3cb711b0b7f346e63e1efb4ed1a741637a58230d00b12af57c9b7d2308d78094ae1a6c1cd12b79ce608a82720fb6b547e34fc833d2e156872eab64f811b4d00c5f4bfabb8893d1e1729b4ba3b0d1f794fc8900ab809a07fc330e5e6fa5516e422bf00dad746cfb0944bfd3a931f3f73330152f15b15f542644d2b871f9729e2008c74046e63e1c7b8512d2a5d06bbce90b477226d16e58378126b7f76dc7659c40d86031687d26fa112cbb286b45decf6b8405d2c3cc7e547c39fd5b8947e3b16fe1ed0e4d46d9f0237480093e97f97708be93f3dd7a816454c42c389ecad33697b4919168e4ac7053e324d9371931beb5705f751b41a4b2953ba343d6573f9f1b3623ca4287e8b6d206140af0043e0476500073357867a6c286e63e1336e207678be1f7841ba0cc0746a3674e2a03f88e15ba665db567f30805f0337f6d3b49dc41aac3650200d09431884270c46a0c73efb2dfc98b83ae4db8e4d0bf7685c885b02351871f9d1f0878e8b449500b61d791cb5bc0c37a65d390437155960ccb2b6b374b9db34394ddba71f175c1999fe678f1b721f15d37f0c9fe91f9efbbd410c07e810d645d77399fe8598a6edc8ef942cf439d27f1894cf17a6ff64be90942465c2f932bf0066c45bcd6541be30cc29de327ca139b751ac6536b59b6618e0ffe27c8017f841a351876ee27e83fc81eb5a98ccc1c0b5e11fcb84b793d54e9abfc25bc3f77d9ef3401ff12ff16285638feb8251802f46d73edb71e1519089943412be210137e45f225ee58c99538521d3527369db45c95b319bdaa7eef929c645d05833fdef0a6eb01b88e89fe71a0c33d3bfe2445c12e8df848a4dd3f37ca67fce9facf692592c62fa67510d6a896701d412d37fdc768be692a00d204b50245325bf92e44cc16ba0cabf8da4af42bee0f2a1cabd2dc20f15d91549660b0b6f85de9096c097ec4f881a33558a7f184986d0599ee7312be7adab19cd3df81beaf57cd4ef4007d15704547319dd3342ea5a4ae073bd924584d4db10d73f58a014d74b90e35f4830f0400252e4da1552e5628fc74553491a3eaedb9a5fabfcafa1d8bb5588d2f1451f7421868d3bbd9543da45bf22695dc9b8ebb719ac123c45765c0a10582429af5797cff47ca187673c2e31fdeb156bdc7c61f8ba9fabcc9714fd735d5042d33fab7e22fa476aa4f918d17f84e168f831fd6baa48f2810ff95e42ff2a47ff8ecd23971b170bb5dc4286a4560d79bc517c8a9e09ef50885c7e183df31615185d2e5fd31c360d609bd9fc227cb6fc45741cc329e09683237123ac4cc2b0047eb42e005cd4d4c46a38b23e86241a40de60e0c132e538b6c165f135c2d3b845bcc610b2143eb45d450ac1187fa403cf83ad1a6e000bfd66806c24cd4c793d9702f4141bd2f6dd1b9780fa099e4d11af13e91615f0a45ec1c995cd8f20631f02fe512fb1df93ccf43fd415cae45bc9b5e8b660bf0919d0d40b191f726257d8d386ae85cbc7f269825b322ec57e8b698ce749395da5c63dca87bf8c7077c605ca0744ff93cc1791edf3f2f96250193aa384f40f7cc8321ca03cc3b084097f99c4a4601e84b6f06cbba6940fcf31fd97e030643e46f49f1917108e506e4ae12f94a631c0c332ed225d1165484bef00699058bd16d187e081238832971f3fb3971d63532c13fbe0957eab0943f12c411c44b6cc68dc34ff1e0e9f7badd7efab586b9d4abd5e60dbb68bf2aa091b282889fb38d028d996a9353bb9b6ab12f832326044bc1f290c4723209d31afea116eb8d336b02ea0c8205ef3052bc3796c2ab67d26e322b946a627a58c48d6a3055ea4c722f7cc7c45f37691fc2f4edc769c67d9a4526f435eeb359ec9db800a20ad1b4698fa368881131ac94e3f914f755b764e9385beddc5711122a6ff89711323e70bd7e27a81e5d49c46cd342d514806322a13883e1e38cbae09e04cb83ae671c8b71df70d32c121a219a6ff2827a1ff10694c8270246501ff48a70ccf160b555ad34effe81d0d3f879c2ff2f9f1b3f6bf2afb36ce37867c9bc0e7a36e451c46e256013ef442bd51074d3f2fc428a686549e35acc0b31b0de059c1c04d7fdbacc3426246f50e693b81234938952f84e7ba612408f044e73d11901d28cff11419eb14588e153cbea20cffdd1917b2e6f04123c53a20a1351a8a2984fb2d24cb20350fe47ec1720f4ad721f1d340b04e21dd9fa9e7682b2272f9fcac2219bef45bde3ff2d895c2471c500113627e902f63e3c49b094d0eebdb5d1817962295982d6e062a87ec8586232a2703f5de75e44d01a81c5c94b086c18fe95fa6680638e0c063facf8d0bd23f486a48ffe4119ae913911e178b340b2160cf7c41906c161d950b8987c1b329881653f9b2a47c5c26ca57c5f279384268c2a793e87938980372ac1802478dc407e4509a35d2279ff55abd8e6db675cbb1df6896356ab520f0454431aee7e1bfda8513e8de2cb48b552c8620b954af1960e087a5c1f7f53e9ce6b0c6138b4abbee70efc7e5239c75f942ffa4da5ee867118f4b7ebc341c1d5200f13784a67bcd890ae3a2783f2141af1522fb41dd838fd23b6bbbf52420358086afc78bd542127996c60acb189a9ba0de12d660acd7a25a2c82631ac8d1c8082d599366d22c35092b23820c7b25e879cc37b815ac86c5ba58563075df8a543fe3b325343ee5f44cb594d061bafcb0712f1b97327ace8f4b399ce4999937d6386e7e8d1b773d97010dabd634cac4a2aabc09760e86158660aa03c6e4a76815da6245b414a6e81f4a61324c4d633c2e3c164cff445c49f904a6d6a3ebf65a2ad45c99fd148496a964c4c942b62332b72b96618595f6852f9421be0eb4682430b36522f8ecf119e52765884645824f0e4e09fc6c19c28d998f0a7c0ff3035d067836d52bfbbd1e9fb289bfa51580c58868d58a7136e2ba883a43daf907be0b6a6cb491198c55c4fb917ac87e6169f82c05e86f81a399a5edc2ba82516d17be7e9b1bafe819aa65bb8691cd8f2898d6210192601044784a773088e184645b89be454d4edc2eea9f1015a412fdda10419bf9485217e9ea14ee0812dc0c11e1837c0ade9a86ce277b2bf5b68965e02d685b41df2065f42dc3d17d087c9fed71bc9a120d842ae1c2f1b81b457a4e6892fa6714cdab21349f1b97727a1e32a6b9f992a1b7681d1d4dcf63c61ddf82846fd51a7a11da41c205c5b4019aeff5429e3bd83ad45025b414b2450fe91fe42a96acd3b8a1dc9ad0bf9e2fd1b741c95c9686c59b3c696a5d301bb1f2cf329edbc3cb686e57fcb65219a2924219fe76086e92ad5a72143e7a3f82f3cd75c9e8409c1ee9b9dd6ab144a3e27d6cf42d883ba060cab75d90090a951c9261127713a08d82e18865e9180eace63016351083b5924c26df0a5ec947f6e1c8b6a7714be0e346506af1dfa731ced54b330a442258cd7063cf321d115fd4578afb849f257aa70009599293225313300512554c2b3aeb9482cfcf21d365213fd56f25f9f133ab7c40aa2a2f2351c764225f13927180c1822cd68700631a4d0f51df8ea1e761345f1817396c5c46d37c09fd33571d47cf65f0633896e9d8f5a6985d92a8fd69faa217041ec9aa22377631fdf3415a4324b801fddb9613d36732ee90b2f49f9ecb960847454801a5e2a8f8291173172322b0206d5583af2588d4db705cede3e09398a21cdbb14c33f71694d83031e1b959af2b915e4471a5916428e2dac9e22b692f162f66980fa2ea60e0eab9c17191a25f1881bae3506c91a43cb7510835bedfc6b55d44b5c8685b96b4371205f037b22f062eb924044a63ae8d5e0697471e80db50905cb0f5c082d05106e5203353afa1fb5c684d9028ab57a888d85014282f13aa30132b4a4b76511996e3f88054f65b16d152b517e087b3a5c949c765aaf92262fadf196e8ed3044db6d88564390de91b41bf971e7758bb075d97780a61e5b3ee45c702acd51cc9f493a149b2bf8e1c170b9d267d812626ada5cf24a41d5fd0742ee3a0d045cced0295cbe7bfc3ecdb61f0599f64460a9c38e1cc89709b02be7eeb47b6242d11e85f368a295e6f45e62d749be7476db718ab5cff2817a52ef675a2d76c10a25fd8845b960dd0615df053ad11d1aa30b6dfe29e89c7257aad8d18e8091e80802fcbc605774d9e87fe696eb64364d6e615c941069e700b846d3b51d568f6068d8f6588d271a70393c8d0524d4bff443daf8c62bb446a5c8af4a0c1e13e7be8b833f2a619663a46ff2bc8bb43f76d297cb473177a3e033fd5f359f8f479765c66325f1063a27fc5f2c5b8f9520adfb6ebbbc48f389956cdb47cd7edd37441fa670bb5c63320dcc89d81e99ff6d2e976aa406b09c68c8ba174888cd848a29f4564361165f971f9e46d365f4f6da179ff38f8426b58b370c2146e53c08f71d347d914fda69e47e447b280e4ad4c1abe0f7beb5ecf07a655800313bc5eaba1b08a9a3dc92a23c1dae050db7fabf49be476492db291f84cbf22c247117c5d9e9c4b800979a00eeabbfd81db7751d7cebee9faa8b9e2931a069eed356c3c3963d76b75901fe1210cb56749824f063e8be421c93e81e0398fb25748dc2ff6b699785c86d1d5e8714f8d97c62124c310e33616be10296fc961f0478ecb2ecc1791f461a5f992cf073d8333d3fd5a69aad55bb0ef9b9b13000010004944415415ab4aff193c133a193b2e16ee6840eb6168e5bcf68e899e2dea7f93caa4f3e3675ff828ea93db55b18c3eb7a2a3ff0c852f706b19e0d98a1c1c538cc06d2cfcd1b88d812f156f8db8edfaf4970ad1cb2944473ed8f9c3ac37d08b586b70ea4ecd2241232a4fa7344cd8bee08c466d6e15dcb49f0d9ae9203ff6254970a06793f8024c400f74842a952f634c7dc40dfdf5c9f0458eb90c33f6c042153509331629cea2ba70729bb4b5e0536686b630525fb1b5651fc765af687228fcddc0cdd4f4cfcc7062dca4ac3717c49ea47ab33d58eb33fd330f124a6bfaea20a6d97666be20ce614cff95c605694e920647929674d833c5ee21e58aca3da332ab2c9f9f495018faada46f29ae8a12fa2447a64c28741c96e9e08fc66d287c83ec936475a6f949f9b8151a6c773acc09b05ec5273f42eea856ab096605723ad1e5e9db40f24a3e1a37ee6753ea7a8536aa32fc18265a64c1243be80fc046d8efbb3ec845b82f8cf1a13e0c91095a8603a9e6d41a48251679ee935d358d5bfc8c9ed6b4e7f7516e463ba0d2b16c26eab7dd1e973ccd4c027f046d4f48ffb3c72d45ff95e74b269fe42329f62481b4de5a584ad35b8afecd0c5dc93cfd0f1d77ddcf9afe2df2d613d1af2cfc523e31b6ac2e8695e80899cd8dc957a4adacfacbe56155802960aaa16f27823945ed710edaf8a93d61d222e587fd7e8f3dc144acdf15fa447bdda92333e2fc18a620fb34e794d54ec731a21d59dc6fb95fda76a1758c4e4db270ab2983f762a6f615c2a06f36c59a31b4fa46eff3c352c891b41c84d48ae8549da8dcf37b3f2ed5dfea3037828e6d44149ba16a5a9f952ca3f614cda767844ce8dfc06725e34b1af4afcad0ff143da3e95f4eda3320db1ac6f4fe4753241b7603a6e37b0341ded8b584fe533d105117f55e595b34fd8b84fe55c0df5aa1d6906b85388f5ffc8c7bc5e834663a3f7ea6a929f48e80f3d9f7d4489e4574082d0c8b7074bd426a1577390e65b8d1336d33381042a10c199c78233b14ff18bea04d560c336e3b6867508d5df6ad659b208a809db30053b15e2f879b8e89c3fe2906dbb3cbf0c173db21d8f2f0d0056a9fd9ff35b2b5f3334ac026872e60d57dae3ff9689948da4ef901334b428cf1d1fd135943b
